import requests
import os

def relationResolver(uri):
    ApiKey = os.getenv("UMLS-ApiKey")
    payload = {"apiKey":ApiKey}
    r = requests.get(uri, params=payload)
    response = r.json()   

    rels = response["result"]
    relList = list()

    for rel in rels:
        relDict = {}
        try:
            relDict["entity1"] = rel["relatedFromIdName"]
        except:
            relDict["entity1"] = "Null"
        relDict["entity2"] = rel["relatedIdName"]
        relDict["relation"] = rel["additionalRelationLabel"]
        relDict["relDescription"] = rel["relationLabel"]
        try:
            relDict["entity1Uri"] = rel["relatedFromId"]
        except:
            relDict["entity1Uri"] = "Null"
        relDict["entity2Uri"] = rel["relatedId"]
        relDict["RUI"] = rel["ui"]
        relDict["rootSource"] = rel["rootSource"]
        relList.append(relDict)
    return relList

# relationResolver("https://uts-ws.nlm.nih.gov/rest/content/2024AA/CUI/C0027358/relations")

# Response Sample:
# {
#   "pageSize": 25,
#   "pageNumber": 1,
#   "pageCount": 31,
#   "result": [
#     {
#       "ui": "R119294259",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "RXNORM",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomClusterRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/source/RXNORM/7242",
#       "relatedFromIdName": "naloxone",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "part_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/source/RXNORM/1007909",
#       "relatedIdName": "naloxone / tilidine"
#     },
#     {
#       "ui": "R133686491",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "RXNORM",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomClusterRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/source/RXNORM/7242",
#       "relatedFromIdName": "naloxone",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "ingredient_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/source/RXNORM/1294831",
#       "relatedIdName": "buprenorphine / naloxone Sublingual Product"
#     },
#     {
#       "ui": "R148170503",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MSH",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomClusterRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/source/MSH/D009270",
#       "relatedFromIdName": "Naloxone",
#       "relationLabel": "RB",
#       "additionalRelationLabel": "mapped_from",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/source/MSH/C557247",
#       "relatedIdName": "oxycodone naloxone combination"
#     },
#     {
#       "ui": "R194251427",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A21151443",
#       "relatedFromIdName": "NALOXONE",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A31646018",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 2 mg / NALOXONE HYDROCHLORIDE DIHYDRATE 0.5 mg SUBLINGUAL FILM"
#     },
#     {
#       "ui": "R183144482",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MMSL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A18538149",
#       "relatedFromIdName": "naloxone",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "ingredient_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A30299456",
#       "relatedIdName": "Buprenorphine-Naloxone, 2 mg-0.5 mg sublingual film"
#     },
#     {
#       "ui": "R178777941",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A24111920",
#       "relatedFromIdName": "Naloxone",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_ingredient_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A29373441",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 2 mg / Naloxone 0.5 mg SUBLINGUAL FILM, SOLUBLE"
#     },
#     {
#       "ui": "R150946169",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A24112605",
#       "relatedFromIdName": "naloxone",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A18500924",
#       "relatedIdName": "buprenorphine hydrochloride 2 mg / naloxone hydrochloride 0.5 mg SUBLINGUAL FILM, SOLUBLE [Suboxone]"
#     },
#     {
#       "ui": "R192998358",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "RXNORM",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomClusterRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/source/RXNORM/7242",
#       "relatedFromIdName": "naloxone",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "ingredient_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/source/RXNORM/2269593",
#       "relatedIdName": "buprenorphine / naloxone Sublingual Film"
#     },
#     {
#       "ui": "R122673151",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "VANDF",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A8437957",
#       "relatedFromIdName": "NALOXONE",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "ingredient_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A18725816",
#       "relatedIdName": "BUPRENORPHINE 2MG/NALOXONE 0.5MG FILM,SUBLINGUAL"
#     },
#     {
#       "ui": "R178770186",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A24111920",
#       "relatedFromIdName": "Naloxone",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A29373440",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 2 mg / Naloxone 0.5 mg BUCCAL FILM, SOLUBLE"
#     },
#     {
#       "ui": "R178762665",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A24111920",
#       "relatedFromIdName": "Naloxone",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A29373441",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 2 mg / Naloxone 0.5 mg SUBLINGUAL FILM, SOLUBLE"
#     },
#     {
#       "ui": "R121567428",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MMSL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A18538149",
#       "relatedFromIdName": "naloxone",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "ingredient_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A18538478",
#       "relatedIdName": "buprenorphine-naloxone 2 mg-0.5 mg sublingual film"
#     },
#     {
#       "ui": "R182805421",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A21151443",
#       "relatedFromIdName": "NALOXONE",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A30272023",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 2 mg / NALOXONE HYDROCHLORIDE DIHYDRATE 0.5 mg SUBLINGUAL FILM [Buprenorphine and Naloxone Sublingual Film]"
#     },
#     {
#       "ui": "R182798676",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A21151443",
#       "relatedFromIdName": "NALOXONE",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A30273144",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 2 mg / NALOXONE HYDROCHLORIDE DIHYDRATE 0.5 mg BUCCAL FILM [Buprenorphine and Naloxone Sublingual Film]"
#     },
#     {
#       "ui": "R194445156",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A21151443",
#       "relatedFromIdName": "NALOXONE",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A31646017",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 2 mg / NALOXONE HYDROCHLORIDE DIHYDRATE 0.5 mg BUCCAL FILM"
#     },
#     {
#       "ui": "R121567183",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MMSL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A18538149",
#       "relatedFromIdName": "naloxone",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "ingredient_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A18534221",
#       "relatedIdName": "Suboxone, 2 mg-0.5 mg sublingual film"
#     },
#     {
#       "ui": "R178770185",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A24111920",
#       "relatedFromIdName": "Naloxone",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_ingredient_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A29373440",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 2 mg / Naloxone 0.5 mg BUCCAL FILM, SOLUBLE"
#     },
#     {
#       "ui": "R161429906",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A24112605",
#       "relatedFromIdName": "naloxone",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A26455088",
#       "relatedIdName": "buprenorphine hydrochloride 2 mg / naloxone hydrochloride 0.5 mg BUCCAL FILM, SOLUBLE [Suboxone]"
#     },
#     {
#       "ui": "R178777950",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A21151443",
#       "relatedFromIdName": "NALOXONE",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A29372881",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 8 mg / Naloxone 2 mg BUCCAL FILM, SOLUBLE"
#     },
#     {
#       "ui": "R220432050",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A21151443",
#       "relatedFromIdName": "NALOXONE",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A36198937",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 8 mg / NALOXONE HYDROCHLORIDE DIHYDRATE 2 mg SUBLINGUAL FILM"
#     },
#     {
#       "ui": "R178776089",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A21151443",
#       "relatedFromIdName": "NALOXONE",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A29372333",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 8 mg / NALOXONE HYDROCHLORIDE 2 mg SUBLINGUAL FILM, SOLUBLE [Suboxone]"
#     },
#     {
#       "ui": "R178800946",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A21151443",
#       "relatedFromIdName": "NALOXONE",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A29372882",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 8 mg / Naloxone 2 mg SUBLINGUAL FILM, SOLUBLE"
#     },
#     {
#       "ui": "R218311046",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A21151443",
#       "relatedFromIdName": "NALOXONE",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A35792858",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 8 mg / NALOXONE HYDROCHLORIDE 2 mg BUCCAL FILM [Buprenorphine and Naloxone]"
#     },
#     {
#       "ui": "R122673123",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "VANDF",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A8437957",
#       "relatedFromIdName": "NALOXONE",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "ingredient_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A18718871",
#       "relatedIdName": "BUPRENORPHINE 8MG/NALOXONE 2MG FILM,SUBLINGUAL"
#     },
#     {
#       "ui": "R203979084",
#       "suppressible": false,
#       "sourceUi": "NONE",
#       "obsolete": false,
#       "sourceOriginated": false,
#       "rootSource": "MTHSPL",
#       "groupId": "NONE",
#       "attributeCount": 0,
#       "classType": "AtomRelation",
#       "relatedFromId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A21151443",
#       "relatedFromIdName": "NALOXONE",
#       "relationLabel": "RO",
#       "additionalRelationLabel": "active_moiety_of",
#       "relatedId": "https://uts-ws.nlm.nih.gov/rest/content/2024AA/AUI/A32713410",
#       "relatedIdName": "BUPRENORPHINE HYDROCHLORIDE 8 mg / NALOXONE HYDROCHLORIDE DIHYDRATE 2 mg SUBLINGUAL FILM"
#     }
#   ]
# }
