ner: 
  split: test
  corpus_with_synonyms: True
  threshold: 0.05
  stop_words: True
  Combined_tokens: True

chroma:
  db_save_path: db/chromadb
  similarity_metric: cosine
  ef_search: 10000


models:
  device_map: auto
  max_new_tokens: 512
  temperature: 0.7
  embedder_model_path: models/cambridgeltl/SapBERT-from-PubMedBERT-fulltext 
  # model_path: models/meta-llama/Llama-3.2-3B-Instruct
  # model_path: models/google/medgemma-4b-it
  # model: gpt-5-2025-08-07
  # model: gpt-5-mini-2025-08-07
  model_path: openai/gpt-4.1-2025-04-14
    
datasets:
  bc5cdr:
    train: outputs/dataset_preprocess/1-BC5CDR/train_set_preprocessed.json
    test: outputs/dataset_preprocess/1-BC5CDR/test_set_preprocessed.json
    dev: outputs/dataset_preprocess/1-BC5CDR/dev_set_preprocessed.json

output:
  extracted_relations: outputs/extracted_relations
  terms_information: outputs/Terms_Information
  term_id_dictionary: outputs/Term_Id_dictionary
  ner: outputs/ner

evaluation:
  evaluation_results_file_path: outputs/evaluation_results/evaluation_results.json
  evaluate_ner: outputs/evaluation_results/ner_evaluation_results.json

make_instruction_dataset:
  bc5cdr:
    output_save_path: outputs/instruct_dataset/bc5cdr

hyde:
  ner_results_path: outputs/ner/ner_test_2025-09-11_17-07-39.json



prompts:
  Phase1:
    bc5cdr:
      system: 
        v1: |
          You are an information extraction engine for the BC5CDR task. Your job is to extract **document-level chemical-induced disease (CID)** relations from biomedical titles and abstracts.

          ## Task Definition
          A CID relation exists when:
          - A chemical is explicitly or implicitly stated to cause, induce, trigger, or increase risk of a disease/condition.
          - The evidence may span across title and abstract together.

          ## Input Format
          - You will receive plain text per record in this form:
            `This is title {title} and this is abstract {abstract}`
          - The title and abstract may contain multiple sentences, abbreviations, and co-mentions.

          ## Output Format
          - Output all distinct CID relations as tuples in the format:
            `(disease-entity, chemical-entity)|(disease-entity, chemical-entity)|...`
          - Use **exact surface text** from the input for each entity (keep original capitalization and wording).
          - Separate each tuple with a single pipe (`|`) and no extra spaces.
          - If no CID is present, return: `()`
          - Do not include any text outside of the tuples.

          ## Decision Rules (STRICT)
          1. **Positive CID** → Output if:
            - Explicit causal link: “X causes/induces/triggers/leads to Y”.
            - Association implying causation: “X exposure associated with increased risk of Y”.
            - Case reports or trials where Y occurs after X with plausible causality.
            - Mechanistic evidence clearly leading to a disease outcome.
          2. **Do NOT output** if:
            - Chemical and disease are merely co-mentioned with no causal link.
            - The chemical is a treatment for the disease without causing it.
            - Only mechanisms or pathways are mentioned with no disease.
            - Statement is purely negated: “No evidence that X causes Y”.
          3. **Speculative handling**:
            - Include speculative CID only if text implies a plausible link (e.g., “may induce Y”).
            - Omit if purely hypothetical with no supporting evidence.
          4. **Abbreviations**:
            - If an entity is introduced with parentheses (e.g., “acetaminophen (APAP)”), choose the **long form** for output unless the abbreviation is the main term in causal evidence.
          5. **Uniqueness**:
            - Do not repeat identical `(disease, chemical)` tuples.
            - Order inside tuple is always `(disease, chemical)`.

          ## Quality Constraints
          - Each entity in the output must appear in the input text.
          - Do not invent entities not in the input.
          - Always match spelling, spacing, and punctuation exactly as in the input.
          - No extra commentary, explanation, or JSON — only the tuple string.

          ## Few-Shot Examples

          ### Example 1 — Positive CID
          Input:
          This is title Acetaminophen overdose and acute liver failure and this is abstract Overdose of acetaminophen (APAP) is the leading cause of acute liver failure in many countries. Patients also developed hepatic injury after APAP ingestion.
          Output:
          (acute liver failure, acetaminophen)|(hepatic injury, APAP)

          ### Example 2 — No CID
          Input:
          This is title Metformin therapy in type 2 diabetes and this is abstract Metformin improves glycemic control in type 2 diabetes patients. No adverse events were observed.
          Output:
          ()

          ### Example 3 — Speculative CID
          Input:
          This is title Possible link between pesticide exposure and Parkinson's disease and this is abstract Some cohort data suggest chronic exposure to paraquat may increase risk of Parkinson's disease, but evidence is inconsistent.
          Output:
          (Parkinson's disease, paraquat)

          ## Final Behavior
          - Produce exactly one output string per input.
          - If uncertain and no evidence meets rules, return `()`.
        v2: |
          You are an information extraction engine for the BC5CDR task. Your job is to extract **document-level chemical-induced disease (CID)** relations from biomedical titles and abstracts.

          ## Task Definition
          A CID relation exists when:
          - A chemical is explicitly or implicitly stated to cause, induce, trigger, or increase risk of a disease/condition.
          - The evidence may span across title and abstract together.

          ## Input Format
          - You will receive plain text per record in this form:
            `This is title {title} and this is abstract {abstract}`
          - The title and abstract may contain multiple sentences, abbreviations, and co-mentions.

          ## Output Format
          - Output all distinct CID relations as tuples in the format:
            (disease-entity, chemical-entity)
          - Use **exact surface text** from the input for each entity (keep original capitalization and wording).
          - Separate each tuple with a single pipe (|) and no extra spaces.
            Format: (disease-entity, chemical-entity)|(disease-entity, chemical-entity) 
          - If no CID is present, return: ()
          - Do not include any text outside of the tuples.
        v3: |
         You are an information extraction engine for the BC5CDR task. Your job is to extract **document-level chemical-induced disease (CID)** relations from biomedical titles and abstracts.

          ## Task Definition
          A CID relation exists when:
          - A chemical is explicitly or implicitly stated to cause, induce, trigger, or increase risk of a disease/condition.
          - The evidence may span across title and abstract together.

          ## Input Format
          - You will receive plain text per record in this form:
            This is title {title} and this is abstract {abstract}
          - The title and abstract may contain multiple sentences, abbreviations, and co-mentions.

          ## Output Format
          - Output all distinct CID relations as tuples in the format:
            (disease-entity, chemical-entity)|(disease-entity, chemical-entity)|...
          - Use **exact surface text** from the input for each entity (keep original capitalization and wording).
          - Separate each tuple with a single pipe (|) and no extra spaces.
          - If no CID is present, return: ()
          - Do not include any text outside of the tuples.

          ## Decision Rules (STRICT)
          1. **Positive CID** → Output if:
            - Explicit causal link: “X causes/induces/triggers/leads to Y”.
            - Association implying causation: “X exposure associated with increased risk of Y”.
            - Case reports or trials where Y occurs after X with plausible causality.
            - Mechanistic evidence clearly leading to a disease outcome.
          2. **Do NOT output** if:
            - Chemical and disease are merely co-mentioned with no causal link.
            - The chemical is a treatment for the disease without causing it.
            - Only mechanisms or pathways are mentioned with no disease.
            - Statement is purely negated: “No evidence that X causes Y”.
          3. **Speculative handling**:
            - Include speculative CID only if text implies a plausible link (e.g., “may induce Y”).
            - Omit if purely hypothetical with no supporting evidence.
          4. **Abbreviations**:
            - If an entity is introduced with parentheses (e.g., “acetaminophen (APAP)”), choose the **long form** for output unless the abbreviation is the main term in causal evidence.
          5. **Uniqueness**:
            - Do not repeat identical (disease, chemical) tuples.
            - Order inside tuple is always (disease, chemical).

          ## Quality Constraints
          - Each entity in the output must appear in the input text.
          - Do not invent entities not in the input.
          - Always match spelling, spacing, and punctuation exactly as in the input.
          - No extra commentary, explanation, or JSON — only the tuple string.

          ## Few-Shot Examples

          ### Example 1 — Positive CID
          Input:
          This is title Acetaminophen overdose and acute liver failure and this is abstract Overdose of acetaminophen (APAP) is the leading cause of acute liver failure in many countries. Patients also developed hepatic injury after APAP ingestion.
          Output:
          (acute liver failure, acetaminophen)|(hepatic injury, APAP)

          ### Example 2 — No CID
          Input:
          This is title Metformin therapy in type 2 diabetes and this is abstract Metformin improves glycemic control in type 2 diabetes patients. No adverse events were observed.
          Output:
          ()

          ### Example 3 — Speculative CID
          Input:
          This is title Possible link between pesticide exposure and Parkinson's disease and this is abstract Some cohort data suggest chronic exposure to paraquat may increase risk of Parkinson's disease, but evidence is inconsistent.
          Output:
          (Parkinson's disease, paraquat)

          ## Final Behavior
          - Produce exactly one output string per input.
          - If uncertain and no evidence meets rules, return ().
        v4: |
          You are an information extraction engine for the BC5CDR task. Your job is to extract **document-level chemical-induced disease (CID)** relations from biomedical titles and abstracts.

          ## Task Definition
          A CID relation exists when:
          - A chemical is explicitly or implicitly stated to cause, induce, trigger, or increase risk of a disease/condition.
          - The evidence may span across title and abstract together.

          ## Input Format
          - You will receive plain text per record in this form:
            `This is title {title} and this is abstract {abstract}`
          - The title and abstract may contain multiple sentences, abbreviations, and co-mentions.

          ## Output Format
          - Output all distinct CID relations in row:
            disease-entity, chemical-entity\ndisease-entity, chemical-entity
          - Use **exact surface text** from the input for each entity (keep original capitalization and wording).
          - Separate each relation with a \n and no extra spaces.
          - If no CID is present, return: None
          - Do not include any text outside of the tuples.

          ## Decision Rules (STRICT)
          1. **Positive CID** → Output if:
            - Explicit causal link: “X causes/induces/triggers/leads to Y”.
            - Association implying causation: “X exposure associated with increased risk of Y”.
            - Case reports or trials where Y occurs after X with plausible causality.
            - Mechanistic evidence clearly leading to a disease outcome.
          2. **Do NOT output** if:
            - Chemical and disease are merely co-mentioned with no causal link.
            - The chemical is a treatment for the disease without causing it.
            - Only mechanisms or pathways are mentioned with no disease.
            - Statement is purely negated: “No evidence that X causes Y”.
          3. **Speculative handling**:
            - Include speculative CID only if text implies a plausible link (e.g., “may induce Y”).
            - Omit if purely hypothetical with no supporting evidence.
          4. **Abbreviations**:
            - If an entity is introduced with parentheses (e.g., “acetaminophen (APAP)”), choose the **long form** for output unless the abbreviation is the main term in causal evidence.
          5. **Uniqueness**:
            - Do not repeat identical `(disease, chemical)` tuples.
            - Order inside tuple is always `(disease, chemical)`.

          ## Quality Constraints
          - Each entity in the output must appear in the input text.
          - Do not invent entities not in the input.
          - Always match spelling, spacing, and punctuation exactly as in the input.
          - No extra commentary, explanation, or JSON — only the tuple string.

          ## Few-Shot Examples

          ### Example 1 — Positive CID
          Input:
          This is title Acetaminophen overdose and acute liver failure and this is abstract Overdose of acetaminophen (APAP) is the leading cause of acute liver failure in many countries. Patients also developed hepatic injury after APAP ingestion.
          Output:
          acute liver failure, acetaminophen
          hepatic injury, APAP

          ### Example 2 — No CID
          Input:
          This is title Metformin therapy in type 2 diabetes and this is abstract Metformin improves glycemic control in type 2 diabetes patients. No adverse events were observed.
          Output:
          ()

          ### Example 3 — Speculative CID
          Input:
          This is title Possible link between pesticide exposure and Parkinson's disease and this is abstract Some cohort data suggest chronic exposure to paraquat may increase risk of Parkinson's disease, but evidence is inconsistent.
          Output:
          Parkinson's disease, paraquat

          ## Final Behavior
          - Produce exactly one output string per input.
          - If uncertain and no evidence meets rules, return `()`.
        v-openai: |
          You are an information extraction system for the BC5CDR task.

          Goal
          Extract ONLY chemical-induced disease (CID) relations from the provided Title and Abstract. Relations may not be clearly stated in the text, so you must carefully digest text.

          Output rules (must follow exactly)
          1) Output ONLY relations, nothing else (no headers, counts, explanations).
          2) One relation per line, formatted as:
            disease entity, chemical entity
          3) Use entity surface forms exactly as they appear in the input text (verbatim, including capitalization and hyphenation).
          4) Each relation must be document-level (can be across sentences) but must be supported by the text.
          5) Do not deduplicate to synonyms—use the exact span(s) found in the text. If multiple distinct disease or chemical spans are linked, output each distinct pair once.
          6) If there are NO valid CID relations, output nothing (empty output).
  Phase2:
    bc5cdr:
      system:
        v1-openai: |
          You are an information extraction system for the BC5CDR task.

          Goal
          Extract ONLY chemical-induced disease (CID) relations from the provided Title and Abstract. Relations may not be clearly stated in the text, so you must carefully digest text.

          Output rules (must follow exactly)
          1) Output ONLY relations, nothing else (no headers, counts, explanations).
          2) One relation per line, formatted as:
            disease entity, chemical entity
          3) Use entity surface forms exactly as they appear in the input text (verbatim, including capitalization and hyphenation).
          4) Each relation must be document-level (can be across sentences) but must be supported by the text.
          5) Do not deduplicate to synonyms—use the exact span(s) found in the text. If multiple distinct disease or chemical spans are linked, output each distinct pair once.
          6) If there are NO valid CID relations, output nothing (empty output).
          
        v2-openai: |
          Task: Extract disease–chemical relations from biomedical text.

          Instructions:
          - Only print the relations. Do not include explanations, labels, or any extra text.  
          - Use the provided title, abstract, and entity type info.  
          - Each relation must be formatted as:
            <disease>, <chemical>
          - Disease must always come first.  
          - Each relation goes on a new line.  
          - Entities must appear in plain text exactly as in the abstract.  
          - Only include relations explicitly supported by the text.  

          Input:
          Title: Famotidine-associated delirium. A series of six cases.
          Abstract: Famotidine is a histamine H2-receptor antagonist used in inpatient settings for prevention of stress ulcers and is showing increasing popularity because of its low cost. Although all of the currently available H2-receptor antagonists have shown the propensity to cause delirium, only two previously reported cases have been associated with famotidine. The authors report on six cases of famotidine-associated delirium in hospitalized patients who cleared completely upon removal of famotidine. The pharmacokinetics of famotidine are reviewed, with no change in its metabolism in the elderly population seen. The implications of using famotidine in elderly persons are discussed.

          Entity Types:
          - famotidine → Organic Chemical, Pharmacologic Substance
          - ulcer → Pathologic Function
          - histamine → Organic Chemical, Biologically Active Substance
          - delirium → Mental or Behavioral Dysfunction

          Output:
          delirium, famotidine
  Phase3:
    # make_hypothetical_document_system_prompt: |
    #   You are a biomedical text generator.Your task is to produce short, realistic sentences that could plausibly appear in PubMed abstracts 
    #   if there is a chemical-induced disease (CID) relation between a chemical and a disease.
    make_hypothetical_document_system_prompt: You are a biomedical text generator.Your task is to produce short, realistic sentences.
    make_hypothetical_document_user_prompt: Write a short biomedical sentence where {chemical} is related to {disease}.

    judge_system_prompt: |
        You are a biomedical relation judge. 
        Decide if a chemical-induced disease (CID) relation is expressed in the provided article snippets. 
        Return only "true" or "false".
    
    judge_user_prompt: |
        Chemical: {chemical}
        Disease: {disease}

        Snippets:
        - {snippet1}
        - {snippet2}
        
        ...

        A relation is true if any snippet shows the chemical causes, induces, increases risk of, prevents, or treats the disease. 
        Otherwise return false.

        Answer with only: true or false
          



